language: go

go: 
  - 1.10.x
  - master

install: 
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script: 
  - go test ./protocol
  # - go test ./server
  - go test -v -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
  